### ISSUE TITLE
Needle and Pyhaystack

### ISSUE THREAD

**Issue by nehalecky** [Smart-Green/needle#4]
Hi Needle team.

Connecting SkySpark and Niagara frameworks to harness the significant utility provided by the Python scientific stack is something needed for the building energy community, thanks for your efforts with this. 
Was hoping understand better for the open source community how Needle compares with the [pyhaystack](https://github.com/ChristianTremblay/pyhaystack) library? Browsing across the commit history shows that it is a fork of pyhaystack, and indeed it seems both projects goals are totally aligned.  

I [opened up an issue at Pyhastack to discuss this](https://github.com/ChristianTremblay/pyhaystack/issues/4), and any feedback you had would be appreciated—thanks so much!

**Comment by sudo-Whateverman** [comment]
Thank you very much, we are counting on the community to give insightful input. 
Although we are using a fork of pyhaystack, we have made a few changes to the original code which make a merge problematic. While the author has originally used python2 as for the code, he has since switched to python3. Also, some changes were introduced to make the code work for skyspark. While those changes have made it possible to connect the client to skyspark, we haven't tested it for Niagara.

The best way to solve those issues is by having input from the community regarding the changes to the code to be added. I believe it is better to have 1 library that will be available for both platforms and both versions of python.

**Comment by nehalecky** [comment]
Hey @sudo-Whateverman, thanks for the reply!

> I believe it is better to have 1 library that will be available for both platforms and both versions of python.

This is exactly what should be done. Remember that, because pyhastack and needle but are based on a widely-adopted and general-use language (in Python), overcoming those challenges can be assisted by software engineers from all walks of life—orders of magnitudes more. I encourage that you reach out to the pyhaystack maintainers to ensure this important discussion happens, setting up a technical vision and roadmap, merging the collective development efforts, and then announcing to the building energy communities about it! 

Let us know (@christopher-hartley) how we can help! Thanks!

**Comment by nehalecky** [comment]
Hi @sudo-Whateverman, let's move the discussion to https://github.com/ChristianTremblay/pyhaystack/issues/4. Thanks!
